### PR TITLE
Nr sxs injection devel

### PR DESCRIPTION
**Pull request by prayush**
Hi Ian, Patricia,

This patch will give users the option to use NR waveforms from files conforming to the current SXS data format.

In this format strain modes are stored directly inside groups as individual datasets named 'Y_l2_m2.dat' etc. The names of the groups themselves depend on the source of the data, i.e. finite-radius waveforms have groups named as "R0100.dir", "R0200.dir", etc (i.e. how far from the binary has the waveform been extracted at), and extrapolated (to-null-infinity) waveforms have groups named as "Extrapolated_N2.dir" etc. 

This code has defaults that make sensible choices for these options, e.g. outer-most radius for finite-radius OR Cce-ed waveforms, N=3rd order for extrapolated waveforms. 

This code will read in *non-uniformly* sampled strain modes, interpolate and re-sample them at the required sample rate and scale to the appropriate binary parameters. In addition, the code also conditions (using a Planck-taper window) the start and end of the waveform. 

It would there be useful for creating backwards-compatibility for NR data that has not been converted to your proposed format. Since it does a spline interpolation on raw data, it is slower than reading from spline-data files, but that is unavoidable since the whole point here is to be able to use Raw NR data for injections.

### CODE REVIEW

**Comment by spxiwh** [comment]
Hi Prayush,

Sorry for taking ages to reply to this. Is it possible to convert UseNRinDA.py to use the 4-space indentation convention? With that done I would be happy to merge.

I would alter this a bit to make this a different approximant (ie. NR_hdf_SeXieS) but I can do that once this is merged.

Cheers
Ian

**Comment by prayush** [comment]
Hi Ian,

Changed the indentation to 4-space in UseNRinDA.py. On a related note, any suggestions on how to get the 'numrel_data' information through when trying to use NR waveforms as templates (not injections)? There are not many spare string fields in SnglInspiral tables.

cheers
Prayush

**Comment by spxiwh** [comment]
Any last objections before I merge this?

**Comment by prayush** [comment]
Not from me. Whether to alter this and make a new approximant "NR_hdf_SXS" OR to decipher the "SXS" format from the HDF file's contents (which is what the code is currently doing) is your choice and I'm fine with either of them.

**Comment by spxiwh** [comment]
This is merged, I have also moved the approximant over to 'NR_hdf5_pycbc_sxs' but it still goes by the same code path. Diff here:

https://github.com/spxiwh/pycbc/commit/b913a22a4092455b6257085498dc105558af8abc

**Comment by prayush** [comment]
Looks good, thank you.

**Pull request merged**
